FROM python:3.3.6
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y postgresql-client

RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/
VOLUME [/code]

CMD ["sh", "wait-for-postgres.sh", "db_33", "python", "manage.py", "test"]
